logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.web.client.RestClient: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          truelayer:
            client-id: ${TRUELAYER_CLIENT_ID}
            client-secret: ${TRUELAYER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/truelayer
            scope: info,accounts,balance,transactions,offline_access
        provider:
          truelayer:
            authorization-uri: https://auth.truelayer-sandbox.com?providers=uk-cs-mock%20uk-ob-all%20uk-oauth-all
            token-uri: https://auth.truelayer-sandbox.com/connect/token
            user-info-uri: ${user-info-uri}
            jwk-set-uri: https://auth.truelayer-sandbox.com/.well-known/jwks
            user-name-attribute: full_name
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: Lax

# A placeholder value for the test environment.
truelayer.data-api-base-url: https://api.truelayer-sandbox.com/data/v1
user-info-uri: ${truelayer.data-api-base-url}/info
